package errors

//TODO: personilize error messages!
const (
	ERROR_WRONG_PASSWORD       = "wrong password!"
	WRONG_INPUT                = "wrong input"
	WRONG_VERIFICATION_ID      = "WRONG_VERIFICATION_ID"
	WRONG_PIN                  = "WRONG_PIN"
	EXPIRE_PIN                 = "EXPIRE_PIN"
	EMPTY_VERIFICATION         = "EMPTY_VERIFICATION"
	EMPTY_FIRST_NAME           = "EMPTY_FIRST_NAME"
	EMPTY_LAST_NAME            = "EMPTY_LAST_NAME"
	USER_EXIST                 = "USER_EXIST"
	USER_NOT_EXIST             = "USER_NOT_EXIST"
	VERIFICATION_NOT_EXIST     = "VERIFICATION_NOT_EXIST"
	VERIFICATION_NOT_CONFIRMED = "VERIFICATION_NOT_CONFIRMED"
	DB_ERROR_SAVING            = "DB_ERROR_SAVING"
	REFRESH_TOKEN_NOT_EXIST    = "REFRESH_TOKEN_NOT_EXIST"
	CANT_HANDLE_REFRESH_TOKEN  = "CANT_HANDLE_REFRESH_TOKEN"
	REFRESH_TOKEN_UNVALID      = "REFRESH_TOKEN_UNVALID"
	REFRESH_TOKEN_NOT_A_TOKEN  = "REFRESH_TOKEN_NOT_A_TOKEN"
	REFRESH_TOKEN_EXPIRED      = "REFRESH_TOKEN_EXPIRED"
)
